### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by WaleeTheRobot**
- Added a single print indicator
- Added JSONFile creator to export winning and losing trades in backtesting. This will enable a user to further analyze trades outside of NinjaTrader.
- Updated DataBar to include volume and volume delta for BidAskVolume

### CODE REVIEW

**Comment by rocket003** [comment]
Hi @WaleeTheRobot iam sorry to contact you like this... first really awesome work! I tried to work with your code but iam not that skilled. 

Would it be possible to add the option that the bot enters only when there are imbalances AND volumesequences? or the options to select that the selected entry are AND and not OR.

**Comment by mdeepevil** [comment]
hi @WaleeTheRobot nice project! Thanks for such ideas, and realizations.

**Comment by mdeepevil** [comment]
@WaleeTheRobot, could you please share the best way to contact you? I'm looking to clarify some details and share a few ideas. Additionally, could you specify which type of chart is used in your strategy, as it doesn't seem to be included?

**Comment by mdeepevil** [comment]
> > @WaleeTheRobot, could you please share the best way to contact you? I'm looking to clarify some details and share a few ideas. Additionally, could you specify which type of chart is used in your strategy, as it doesn't seem to be included?
> 
> You can just post it here if you want. You can use whatever type of chart you want, but I primarily use a 15 range chart for ES.

Have you seen the PATI solution? I'm just curious because you're on the right track. I'm sure that most traders who employ such a strategy are now wondering how there can be such a high-quality solution available for free and open source.

**Comment by simox-0850** [comment]
hi man such a great work can you integrate machine learning model to this bot based on tick data history of es for the last 3 month for example like polarity bot

**Pull request merged**
